# Generated by Django 3.0.2 on 2020-08-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-comment_date',)},
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(max_length=264, verbose_name='Put a Good Title'),
        ),
    ]
